### ISSUE TITLE
Consider renaming displayName to title

### ISSUE THREAD

**Issue by alexkreidler** [HydraCG/Heracles.ts#123]
Both `hydra:Class` and `hydra:ApiDocumentation` use:
```ts
    /**
     * Gets a title of this API documentation.
     * @readonly
     * @returns {string}
     */
    readonly displayName?: string;
```

However, the spec uses `hydra:title`. Is this difference meaningful? If not, I think it should probably be renamed in the next breaking version because it could cause some confusion for new users.

Also: maybe the Typescript documentation should link to the relevant properties in the Hydra spec.

**Comment by alien-mcl** [comment]
Hi @alexkreidler 

Reason why the client uses `displayName` is due to fact that it tries to fill that property from a couple of places:
- `hydra:title`
- `rdfs:label`

Same thing goes for `hydra:description`, which will be changed in PR#111 to `textDescription` as it will be filled with:
- `hydra:description`
- `rdfs:comment`

This way the client data model takes off a burden from the developer to pin-point actual label/description to be shown.

I hope this answer is satisfactory to you. Feel free to elaborate more on this issue.
