### ISSUE TITLE
Get class property value

### ISSUE THREAD

**Issue by yngwi** [HydraCG/Heracles.ts#136]
Hi,

I'm trying to loop over a collection and extract the various property values from the members of the collection. Let's say I have the following abbreviated response from my server:

```json
  "member": [
    {
      "@id": "example:2bfd5353-6842-48f7-9f8c-111474f57dfb",
      "@type": "schema:person",
      "label": "Person 1"
    },
    {
      "@id": "example:108d8384-a55a-4b21-8511-654fb3830d5f",
      "@type": "schema:person",
      "label": "Person 2"
    },
  ],
```

Then, I'm looping over the response.

```ts
const data = await Client.getResource(
  "http://localhost:4000/persons"
);
for (const person of data.members) {
  const iri = person.iri;
  const label = person.label; // How can I do this?
}
```

As written in the comment above, how can I get properties apart from IRI and type from the members? I couldn't find an actual example in the documentation, tests, use cases and other places I was looking. Any help is greatly appreciated!

Best,
Daniel

**Comment by alien-mcl** [comment]
Hydra exposes only those thing that it understands - hypermedia controls. That's why you can easily access collection member's. But these will be some basic details like member IRI, it's type (if any), and other hypermedia like links, operations, etc.

In order to grab the real resource you'll have to access the received respone's body. Hydra mimics standard Response class members like body, json, headers etc.

Following your snipped, I think it would look like the this:
```typescript
const data = await Client.getResource(
  "http://localhost:4000/persons"
);
const graph = await jsonld.expand(await data.json());
for (const person of data.members) {
  const personResource = graph["@graph"].find(_ => _["@id"] === person.iri);
  const label = personResource["http://some.uri/vocab#label][0]["@value"];
}
```

I may think about adding actual resources to those hypermedia controls - not trivial due to various RDF representations, but I'l try to figure it out.

**Comment by yngwi** [comment]
Sorry about not answering earlier. Thank you for your reply. In the mean time I have come to the same conclusion and have added something along the line of what you post in my code but it is nice to have it confirmed "officially". To me what you say makes sense but I was wondering if I had a misunderstanding and it *should* be possible.

Again, thank you.
