### ISSUE TITLE
How should Heracle's internal data model look like?

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Heracles.ts#8]
Currently it uses JSON-LD framing to get to a specific JSON-LD representation.

**Comment by tpluscode** [comment]
My concerns with JSON-LD API functions are that 

1. in some cases (framing in particular), objects get duplicated. that's why originally I processed the representation to create a fully navigable JavaScript object graph (aka. the `objectify()` function missing from JSON-LD spec)
2. it's sometimes awkward to get the desired information from a JSON-LD tree. at least without reframing with different settings multiple times. in other words there is no one JSON-LD tree which will serve all Heracles' needs 

Doing the `objectify()` processing allowed me to retain the JSON-LD shape whilst adding convenience getters/setters for built-in Hydra properties and also those possibly not explicitly stated in a particular representation. An example are partial collections, where additional processing allows simply traversing the collection/view objects with native JS.

And I hit an issue with `2` around collections as well when I wanted to get the parent collection from a partial view resource. At that point I resorted to SPARQL where it's a simple query with subject and object reversed. I'm sure there is a better solution though and I do hope so because the SPARQL-able implementations for browsers are lacking or quite heavy :(

**Comment by tpluscode** [comment]
Oh, and regarding JSON-LD API functions - cycles will be a problem when representing a graph as tree. There is only as far as a frame can get us.

**Comment by elf-pavlik** [comment]
In [the last telecon minutes](http://www.hydra-cg.com/minutes/2017-07-10/) I see rdf-ext mentioned. I think @bergos would offer his help with potentially adopting it. Possibly another relevant reference - draft for RDF/JS High Level API https://github.com/rdfjs/representation-task-force/pull/95

**Comment by elf-pavlik** [comment]
What does it currently takes to add support for parsing responses with those content types
* 'text/turtle'
* 'text/trig'
* 'text/n-triples'
* 'text/n-quads'
* 'text/n3' (optional)

[N3.js](https://github.com/RubenVerborgh/N3.js) supports parsing all of them.

**Comment by alien-mcl** [comment]
As for support of other RDF serialization, I've added a separate issue #69 for that.
For the data model - JSON-LD framing is used no more for quite some time in favor of internal mechanism for build the data model used by the client internally making this issue obsolete.

For details please refer to the [docs](https://github.com/HydraCG/Heracles.ts/tree/master/docs) and the `DataModel` namespace types description.
